[build]
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"
  # Ignore secrets scanning in documentation files
  SECRETS_SCAN_OMIT_PATHS = ".env.example,.gitignore,QUICK_START.md,SETUP.md,docs/SETUP_NETLIFY.md,docs/SETUP_SUPABASE.md,README.md"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200